build:
   image: python:2.7
   commands: 
      - python -v
      - pip install ansible
      - pip install simplejson
      - cd tests
      - ansible-galaxy install novuso.php-ext
      - "ansible-playbook playbook.yml --syntax-check"
      - "ansible-playbook playbook.yml --connection=local"
      - >
        ansible-playbook playbook.yml --connection=local
        | grep -q 'changed=0.*failed=0'
        && (echo 'Idempotence test: pass' && exit 0)
        || (echo 'Idempotence test: fail' && exit 1)
